plugins:
    - name: "EssentialsX"
      url: "https://ci.ender.zone/job/EssentialsX/lastSuccessfulBuild/artifact/Essentials/target/EssentialsX-2.17.1.12.jar" 
    - name: "EssentialsXChat"
      url: "https://ci.ender.zone/job/EssentialsX/lastSuccessfulBuild/artifact/EssentialsChat/target/EssentialsXChat-2.17.1.12.jar" 
    - name: "EssentialsXProtect"
      url: "https://ci.ender.zone/job/EssentialsX/lastSuccessfulBuild/artifact/EssentialsProtect/target/EssentialsXProtect-2.17.1.12.jar" 
    - name: "EssentialsXSpawn"
      url: "https://ci.ender.zone/job/EssentialsX/lastSuccessfulBuild/artifact/EssentialsSpawn/target/EssentialsXSpawn-2.17.1.12.jar"
    - name: "AntiGuest"
      url: "https://plik.root.gg/file/0YkuhCUKQybYJo0G/Yjlspc3zXNCfA4pq/AntiGuest.jar"
    - name: "LogBlock"
      url: "https://www.iani.de/jenkins/job/LogBlock/64/artifact/target/LogBlock.jar"
    - name: "Orebfuscator"
      url: "https://github.com/lishid/Orebfuscator/releases/download/4.4.3/orebfuscator-4.4.3.jar"
    - name: "Vault"
      url: "https://plik.root.gg/file/0YkuhCUKQybYJo0G/nDWlSbsWQDemD0gs/Vault.jar" 
    - name: "GroupManager"
      url: "https://github.com/GroupManager/GroupManager/releases/download/v0.1.0/GroupManager.jar" 
